name: Bump version
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  create_minor_tag:
    if: contains(github.head_ref, 'release') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      - name: Bump version and push tag
        id: bump_minor_version_and_push_tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: master
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bump_minor_version_and_push_tag.outputs.new_tag }}
          release_name: Release ${{ steps.bump_minor_version_and_push_tag.outputs.new_tag }}
          body: |
            Changes in this Release
            - 
          draft: true

  create_patch_tag:
    if: contains(github.head_ref, 'hotfix') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'
    - name: Bump patch version and push tag
      id: bump_patch_version_and_push_tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.bump_patch_version_and_push_tag.outputs.new_tag }}
        release_name: Release ${{ steps.bump_patch_version_and_push_tag.outputs.new_tag }}
        body: |
          Changes in this Release
          - 
        draft: true